project:
  type: website

website:
  title: "@kapitan"
  navbar:
    logo: images/logo-150px.png
    title: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  search:
    location: navbar
    type: textbox

format:
  html:
    theme:
      light:
        - flatly
        - mozilla.scss
      dark:
        - darkly
        - mozilla.scss
    css: styles.css
    toc: true



