project:
  type: website

website:
  title: "@kapitan"
  reader-mode: true
  search:
    location: navbar
    type: textbox
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: docs/projects/index.qmd
        text: "Projects"
      - docs/about.qmd
  sidebar:
    - title: "Projects"
      logo: images/logo-150px.png
      style: "docked"
      background: light
      contents:
        - docs/projects/project-1.qmd
        - docs/projects/project-2.qmd


format:
  html:
    theme:
      light:
        - flatly
        - mozilla.scss
      dark:
        - darkly
        - mozilla.scss
    css: styles.css
    toc: true



