project:
  type: website

website:
  title: "@kapitan"
  search:
    location: navbar
    type: textbox
  navbar:
    title: false
    logo: images/@kapitan-logo-redbrick-320x132.png
    pinned: true
    collapse-below: lg
  sidebar:
    - style: floating
      collapse-level: 1
      background: light
      contents:
        - section: "Services"
          contents:
            - docs/mentoring.qmd
            - docs/masterclasses.qmd
        - section: "Projects"
          contents:
            - docs/projects/project-1.qmd
            - docs/projects/project-2.qmd
        - text: "Blog"
          href: docs/blog/listing.qmd
        - text: "About me"
          href: docs/about.qmd


format:
  html:
    theme:
      light:
        - flatly
        - mozilla.scss
    css: styles.css
    toc: true

# filters:
#   - nutshell
