project:
  type: website

website:
  title: "@kapitan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light:
        - flatly
        - mozilla.scss
      dark:
        - darkly
        - mozilla.scss
    css: styles.css
    toc: true



